project:
  type: website
  execute-dir: project
website:
  title: "SaSR03"
  navbar:
    left:
      - href: index.qmd
        text: Home
  sidebar:
    contents:
      - section: "Data Handling"
        contents:
          - text: "Get to know and summarise data"
            href: data_handling/dh_summary.qmd
          - text: "Documenting data"
            href: data_handling/dh_doc.qmd
          - text: "Creating new variables"
            href: data_handling/dh_variables.qmd
          - text: "Selecting cases and repeating analyses for groups"
            href: data_handling/dh_select.qmd
          - text: "Using fuctions"
            href: data_handling/dh_functions.qmd
          - href: data_handling/dh_missing.qmd
            text: "Dealing with missing data"
      - section: "Modelling (Assignments)"
        contents:
          - text: "Simple linear regression"
            href: modelling/glm_regression.qmd
          - text: "Multiple linear regression"
            href: modelling/glm_multiple_regression.qmd
          - text: "Model testing"
            href: modelling/glm_model_testing.qmd
          - text: "Binary logistic regression"
            href: modelling/glm_logistic_regression.qmd
          - text: "Multinomial Logistic Regression"
            href: modelling/glm_multinomial_regression.qmd
          - text: "Ordinal Logistic Regression"
            href: modelling/glm_ordinal_regression.qmd
          - text: "Event history analysis"
            href: modelling/glm_eha.qmd
      - section: "GGPlot"
        contents:
          - text: "Data Visualization with ggplot2"
            href: ggplot/ggplot.qmd
      - section: "Miscellaneous"
        contents:
          - text: "Random sampling"
            href: miscellaneous/random_sampling.qmd
          - text: "Programming features in R"
            href: miscellaneous/r_programming_features.qmd
          - text: "Factor analysis"
            href: miscellaneous/factor_analysis.qmd
          - text: "Reliability"
            href: miscellaneous/reliability.qmd
format:
  html:
    theme: lumen
    toc: true

execute:
  freeze: auto