---
title: "SaSR03"
subtitle: "Methods and Statistics 1: Regression Analysis and its Generalizations"
language:
  title-block-published: "Last update"
date: today
---

This site contains the syllabus for the first part of the course (data handling), as well as the assignments for the second part (modelling). You can also download the contents as a [PDF file](sasr03_dh_syllabus.pdf). The site and the PDF link will always have the most up-to-date contents. If you have downloaded the PDF before, make sure you have the latest version by checking the date. 

You can find the entire course manual, the course package (with datasets and assignment answers), and slides (posted weekly) in Brightspace. 


## Teachers

- [Deni Mazrekaj](https://denimazrekaj.com/) (coordinator), Associate Professor, Department of Sociology, Utrecht University
- [Weverthon Machado](https://www.weverthon.com/), Postdoc, Department of Sociology, Utrecht University



## Acknowledgements

Corrections of and comments on the syllabus text, the example scripts, and answers to selected assignments are solicited. Requests for additions are welcome as well. Future students will appreciate your input! 

The syllabus and assignments for SaSR3 were originally developed by Jeroen Weesie. We acknowledge valuable contributions by former teachers Ozan Aksoy, Jos Dessens, Wim Jansen, Peter van de Heijden, Peter Ligtig, David Macro, and Vardan Barsegyan as well as by numerous students. We thank Bjarne van der Mark for assistance in translating the course materials to R. 