<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.19">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Multiple linear regression – SaSR03</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-bf27225e3a48a9273f3daa8f8e829971.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-60a28a6e58c4296c0bb11f8f5d7a34cd.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@4/tex-chtml.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">SaSR03</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../modelling/regression.html">Modelling (Assignments)</a></li><li class="breadcrumb-item"><a href="../modelling/multiple_regression.html">Multiple linear regression</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Data Handling</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../data_handling/dh_summary.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Get to know and summarise data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../data_handling/dh_variables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Creating new variables</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../data_handling/dh_select.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Selecting cases</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../data_handling/dh_functions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Using functions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../data_handling/dh_missing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Dealing with missing values</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../data_handling/dh_restructure.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Restructuring data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../data_handling/dh_aggregate.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Aggregating data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../data_handling/dh_merge.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Adding cases and variables</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../data_handling/factor_analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Factor analysis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../data_handling/reliability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Reliability</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Modelling (Assignments)</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../modelling/regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Simple linear regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../modelling/multiple_regression.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Multiple linear regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../modelling/model_testing.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Model testing</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../modelling/logistic_regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Binary logistic regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../modelling/multinomial_regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Multinomial Logistic Regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../modelling/ordinal_regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Ordinal Logistic Regression</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../modelling/eha.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Event history analysis</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Extra assignments</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../data_handling/extra_assignment_1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Extra assignment 1</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../modelling/extra_assignment_2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Extra assignment 2</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Miscellaneous</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../miscellaneous/ggplot.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Data Visualization with ggplot2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../miscellaneous/random_sampling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Random sampling</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../miscellaneous/r_programming_features.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Programming features in R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../data_handling/dh_doc.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Documenting data</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#assignments" id="toc-assignments" class="nav-link active" data-scroll-target="#assignments">Assignments</a>
  <ul class="collapse">
  <li><a href="#predicting-a-post-test-score" id="toc-predicting-a-post-test-score" class="nav-link" data-scroll-target="#predicting-a-post-test-score">Predicting a post-test score</a></li>
  <li><a href="#donations-religion-and-income" id="toc-donations-religion-and-income" class="nav-link" data-scroll-target="#donations-religion-and-income">Donations, religion, and income</a></li>
  <li><a href="#occupational-prestige-and-education" id="toc-occupational-prestige-and-education" class="nav-link" data-scroll-target="#occupational-prestige-and-education">Occupational prestige and education</a></li>
  </ul></li>
  <li><a href="#answers" id="toc-answers" class="nav-link" data-scroll-target="#answers">Answers</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../modelling/regression.html">Modelling (Assignments)</a></li><li class="breadcrumb-item"><a href="../modelling/multiple_regression.html">Multiple linear regression</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Multiple linear regression</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="assignments" class="level2">
<h2 class="anchored" data-anchor-id="assignments">Assignments</h2>
<section id="predicting-a-post-test-score" class="level3">
<h3 class="anchored" data-anchor-id="predicting-a-post-test-score">Predicting a post-test score</h3>
<ol type="1">
<li><p>Use the dataset <code>sesam</code>. We predict <code>postnumb</code> (a post-test score) from <code>age</code> and <code>prenumb</code> (a pre-test score).</p>
<ul>
<li><p>Fit a regression of <code>postnumb</code> on <code>age</code> and <code>prenumb</code>. Interpret each coefficient, the intercept, and the <span class="math inline">\(R^2\)</span>. Is <code>age</code> a significant predictor once <code>prenumb</code> is controlled for?</p></li>
<li><p>Fit a regression of <code>postnumb</code> on <code>prenumb</code> alone. Compare the coefficient for <code>prenumb</code> and the <span class="math inline">\(R^2\)</span> to the model that also includes <code>age</code>. What do you conclude?</p></li>
</ul></li>
</ol>
</section>
<section id="donations-religion-and-income" class="level3">
<h3 class="anchored" data-anchor-id="donations-religion-and-income">Donations, religion, and income</h3>
<p>Use the dataset <code>donations</code>, which contains information on voluntary donations.. Treat the “miscellaneous” category of <code>religion</code> as missing, and exclude the corresponding observations from the analyses below (it is too heterogeneous a group to interpret meaningfully).</p>
<ol start="2" type="1">
<li><p>Test whether average donations differ between religious groups, controlling for income (<code>inc</code>). Fit a regression of <code>donation</code> on <code>religion</code> (as a factor) and <code>inc</code>. Which categories differ significantly from the reference category?</p></li>
<li><p>Is there a difference in average donation between two specific religious categories that are <em>not</em> both compared to the reference category in the previous output? For example, is there a significant difference between rereformed and reformed?</p></li>
</ol>
<ul>
<li>One way of testing this is re-running the model with a different reference category. A better way is to use the function <code>avg_comparisons()</code> from package <code>marginaleffects</code>, which you have to install and load. You can obtain pairwise comparisons between all levels of a categorical (i.e.&nbsp;factor) variable with <code>avg_comparisons(your_model_object, variables = list(your_variable_name =  "pairwise"))</code>.</li>
</ul>
<ol start="4" type="1">
<li><p>Donations and income have been recorded in thousands. Look at the variable labels (<code>glimpse(data_frame_name$variable_name)</code>) to check in which time units they are recorded. Construct a new variable <code>propdon</code>, the proportion of monthly income donated. This will be outcome variable for the next questions. Report the mean and standard deviation of <code>propdon</code>. What do these values tell you?</p></li>
<li><p>Fit a regression of <code>propdon</code> on <code>religion</code> and obtain pairwise comparisons between all categories. Between which categories is there evidence of a difference?</p></li>
<li><p>Consider the following hypothesis: donations increase with income when controlling for religion, i.e., people gives a higher fraction of their income, the higher their income (in theoretical terms, charity is a “luxury good”). Fit a regression model to test this and interpret the results.</p></li>
<li><p>Fit a regression of <code>propdon</code> on <code>male</code>, <code>religion</code>, and their interaction. Is there evidence that the effect of religion on donations differs between men and women?</p></li>
<li><p>Fit a regression of <code>propdon</code> on <code>inc</code>, <code>religion</code>, and their interaction. Is there evidence that the effect of income on donations varies between religious denominations?</p></li>
<li><p>Consider whether life events (<code>lifevent</code>) have a larger effect on charity among older people than among younger people. Beware: this formulation does not mean that we want you to dichotomize age. It is just an informal way of expressing that the effect of life events increases with age. Is there evidence that the effect of <code>lifevent</code> on <code>propdon</code> is larger for older people than for younger people?</p></li>
<li><p>Test whether the effect of income on <code>propdon</code> varies with age. (For young people a smaller share of their income is discretionary due to mortgage, children, etc.)</p></li>
<li><p>Test whether the effect of income on <code>propdon</code> varies by gender.</p></li>
<li><p>Test whether the gender difference in income effects varies with religion (Note: this is actually a 3-way interaction).</p></li>
</ol>
</section>
<section id="occupational-prestige-and-education" class="level3">
<h3 class="anchored" data-anchor-id="occupational-prestige-and-education">Occupational prestige and education</h3>
<p>Use the dataset <code>gss91_extended</code>. <span class="citation" data-cites="e">@e</span> want to investigate whether the effect of education (<code>educ</code>) on occupational prestige (<code>prestg80</code>) is nonlinear.</p>
<ol start="13" type="1">
<li>Make a scatterplot of <code>prestg80</code> against <code>educ</code>. Overlay it with both a linear and a quadratic fitted line.</li>
</ol>
<ul>
<li>Tipo: for the quadratic line, use the formula <code>y ~ x + I(x*x)</code> in <code>geom_smooth()</code>.</li>
</ul>
<ol start="14" type="1">
<li><p>Fit a regression model of <code>prestg80</code> on <code>educ</code>, a squared term for <code>educ</code>, and the control variables <code>race</code>, <code>region</code>, and <code>sex</code>. Make sure that the control variables are interpreted as categorical variables, not numeric. Is the squared term statistically significant? What do you conclude about the shape of the relationship?</p></li>
<li><p>Using the coefficients for <code>educ</code> and <code>educ</code><span class="math inline">\(^2\)</span>, compute the turning point of the curve: the value of <code>educ</code> at which expected prestige is at its minimum or maximum. Is the curve U-shaped or inverted-U shaped? Check how many observations in the data actually fall at or below this turning point, and discuss whether the turning point should be interpreted, or whether it is more appropriate to describe the relationship only over the range where most of the data lie.</p></li>
</ol>
</section>
</section>
<section id="answers" class="level2">
<h2 class="anchored" data-anchor-id="answers">Answers</h2>
<div class="callout callout-style-simple callout-note callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>See answers
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.2.1     ✔ readr     2.2.0
✔ forcats   1.0.1     ✔ stringr   1.6.0
✔ ggplot2   4.0.3     ✔ tibble    3.3.1
✔ lubridate 1.9.5     ✔ tidyr     1.3.2
✔ purrr     1.2.2     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(haven)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(janitor)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Attaching package: 'janitor'

The following objects are masked from 'package:stats':

    chisq.test, fisher.test</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(modelsummary)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(marginaleffects)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(skimr)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<section id="predicting-a-post-test-score-1" class="level1">
<h1>Predicting a post-test score</h1>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>sesam <span class="ot">&lt;-</span> <span class="fu">read_dta</span>(<span class="st">"data/sesam.dta"</span>)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>fit_multi <span class="ot">&lt;-</span> <span class="fu">lm</span>(postnumb <span class="sc">~</span> age <span class="sc">+</span> prenumb, <span class="at">data =</span> sesam)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit_multi)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = postnumb ~ age + prenumb, data = sesam)

Residuals:
    Min      1Q  Median      3Q     Max 
-38.130  -6.456  -0.456   5.435  22.568 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   7.4242     5.1854   1.432    0.154    
age           0.1225     0.1084   1.131    0.259    
prenumb       0.7809     0.0637  12.259   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 9.486 on 237 degrees of freedom
Multiple R-squared:  0.4592,    Adjusted R-squared:  0.4547 
F-statistic: 100.6 on 2 and 237 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># E(postnumb) = 7.42 + 0.12 age + 0.78 prenumb      (SE_age = 0.11, SE_prenumb = 0.06)</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Age does not contribute in predicting postnumb (not significant). The #marginal correlation between age and postnumb is significant, but here the effect of age is conditional on that of prenumb: once you control for prenumb, age does not matter. If pretest score goes up by 1, posttest score significantly goes up by 0.78, irrespective of age. People aged 0 with a pretest score of 0 have a posttest score of 7.42; interpreting the constant is not meaningful here. About 45% of the variation in the post-test is explained by the pre-test and age.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>fit_prenumb_only <span class="ot">&lt;-</span> <span class="fu">lm</span>(postnumb <span class="sc">~</span> prenumb, <span class="at">data =</span> sesam)</span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="fu">modelsummary</span>(<span class="fu">list</span>(fit_multi, fit_prenumb_only), <span class="at">stars =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<script src="https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.js"></script>

    <script>
      // Create table-specific functions using external factory
      const tableFns_9lvzcqf35rriw8rxqwy5 = TinyTable.createTableFunctions("tinytable_9lvzcqf35rriw8rxqwy5");
      // tinytable span after
      window.addEventListener('load', function () {
          var cellsToStyle = [
            // tinytable style arrays after
          { positions: [ { i: '14', j: 2 }, { i: '14', j: 3 } ], css_id: 'tinytable_css_2mb8evfo0a80o61qjh7p',}, 
          { positions: [ { i: '6', j: 2 }, { i: '6', j: 3 } ], css_id: 'tinytable_css_5mpd403bsdfq4b7vbo2v',}, 
          { positions: [ { i: '1', j: 2 }, { i: '2', j: 2 }, { i: '3', j: 2 }, { i: '4', j: 2 }, { i: '5', j: 2 }, { i: '7', j: 2 }, { i: '8', j: 2 }, { i: '9', j: 2 }, { i: '10', j: 2 }, { i: '11', j: 2 }, { i: '12', j: 2 }, { i: '13', j: 2 }, { i: '1', j: 3 }, { i: '2', j: 3 }, { i: '3', j: 3 }, { i: '4', j: 3 }, { i: '5', j: 3 }, { i: '7', j: 3 }, { i: '8', j: 3 }, { i: '9', j: 3 }, { i: '10', j: 3 }, { i: '11', j: 3 }, { i: '12', j: 3 }, { i: '13', j: 3 } ], css_id: 'tinytable_css_lhhbpz0w2u6bsr0t9f22',}, 
          { positions: [ { i: '0', j: 2 }, { i: '0', j: 3 } ], css_id: 'tinytable_css_4614cdmbw5zmmzqnvo83',}, 
          { positions: [ { i: '14', j: 1 } ], css_id: 'tinytable_css_pe0th151icqu2c9f2g7t',}, 
          { positions: [ { i: '6', j: 1 } ], css_id: 'tinytable_css_z328hnondy7r5ev92run',}, 
          { positions: [ { i: '1', j: 1 }, { i: '2', j: 1 }, { i: '3', j: 1 }, { i: '4', j: 1 }, { i: '5', j: 1 }, { i: '7', j: 1 }, { i: '8', j: 1 }, { i: '9', j: 1 }, { i: '10', j: 1 }, { i: '11', j: 1 }, { i: '12', j: 1 }, { i: '13', j: 1 } ], css_id: 'tinytable_css_zvnn82ixuul8oakrkwvd',}, 
          { positions: [ { i: '0', j: 1 } ], css_id: 'tinytable_css_o319sf98u4co1896swl7',}, 
          ];

          // Loop over the arrays to style the cells
          cellsToStyle.forEach(function (group) {
              group.positions.forEach(function (cell) {
                  tableFns_9lvzcqf35rriw8rxqwy5.styleCell(cell.i, cell.j, group.css_id);
              });
          });
      });
    </script>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/vincentarelbundock/tinytable@main/inst/tinytable.css">
    <style>
    /* tinytable css entries after */
    #tinytable_9lvzcqf35rriw8rxqwy5 td.tinytable_css_2mb8evfo0a80o61qjh7p, #tinytable_9lvzcqf35rriw8rxqwy5 th.tinytable_css_2mb8evfo0a80o61qjh7p {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --line-type-bottom: solid; --line-type-left: solid; --line-type-right: solid; --line-type-top: solid; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }
    #tinytable_9lvzcqf35rriw8rxqwy5 td.tinytable_css_5mpd403bsdfq4b7vbo2v, #tinytable_9lvzcqf35rriw8rxqwy5 th.tinytable_css_5mpd403bsdfq4b7vbo2v {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --line-type-bottom: solid; --line-type-left: solid; --line-type-right: solid; --line-type-top: solid; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }
    #tinytable_9lvzcqf35rriw8rxqwy5 td.tinytable_css_lhhbpz0w2u6bsr0t9f22, #tinytable_9lvzcqf35rriw8rxqwy5 th.tinytable_css_lhhbpz0w2u6bsr0t9f22 { text-align: center }
    #tinytable_9lvzcqf35rriw8rxqwy5 td.tinytable_css_4614cdmbw5zmmzqnvo83, #tinytable_9lvzcqf35rriw8rxqwy5 th.tinytable_css_4614cdmbw5zmmzqnvo83 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --line-type-bottom: solid; --line-type-left: solid; --line-type-right: solid; --line-type-top: solid; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: center }
    #tinytable_9lvzcqf35rriw8rxqwy5 td.tinytable_css_pe0th151icqu2c9f2g7t, #tinytable_9lvzcqf35rriw8rxqwy5 th.tinytable_css_pe0th151icqu2c9f2g7t {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.08em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --line-type-bottom: solid; --line-type-left: solid; --line-type-right: solid; --line-type-top: solid; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }
    #tinytable_9lvzcqf35rriw8rxqwy5 td.tinytable_css_z328hnondy7r5ev92run, #tinytable_9lvzcqf35rriw8rxqwy5 th.tinytable_css_z328hnondy7r5ev92run {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 0; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.1em; --line-type-bottom: solid; --line-type-left: solid; --line-type-right: solid; --line-type-top: solid; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }
    #tinytable_9lvzcqf35rriw8rxqwy5 td.tinytable_css_zvnn82ixuul8oakrkwvd, #tinytable_9lvzcqf35rriw8rxqwy5 th.tinytable_css_zvnn82ixuul8oakrkwvd { text-align: left }
    #tinytable_9lvzcqf35rriw8rxqwy5 td.tinytable_css_o319sf98u4co1896swl7, #tinytable_9lvzcqf35rriw8rxqwy5 th.tinytable_css_o319sf98u4co1896swl7 {  position: relative; --border-bottom: 1; --border-left: 0; --border-right: 0; --border-top: 1; --line-color-bottom: var(--tt-line-color); --line-color-left: var(--tt-line-color); --line-color-right: var(--tt-line-color); --line-color-top: var(--tt-line-color); --line-width-bottom: 0.05em; --line-width-left: 0.1em; --line-width-right: 0.1em; --line-width-top: 0.08em; --line-type-bottom: solid; --line-type-left: solid; --line-type-right: solid; --line-type-top: solid; --trim-bottom-left: 0%; --trim-bottom-right: 0%; --trim-left-bottom: 0%; --trim-left-top: 0%; --trim-right-bottom: 0%; --trim-right-top: 0%; --trim-top-left: 0%; --trim-top-right: 0%; ; text-align: left }
    </style>
    <div class="container">
      <table class="tinytable" id="tinytable_9lvzcqf35rriw8rxqwy5" style="width: auto; margin-left: auto; margin-right: auto;" data-quarto-disable-processing="true">
        
        <thead>
              <tr>
                <th scope="col" data-row="0" data-col="1"> </th>
                <th scope="col" data-row="0" data-col="2">(1)</th>
                <th scope="col" data-row="0" data-col="3">(2)</th>
              </tr>
        </thead>
        <tfoot><tr><td colspan="3">+ p &lt; 0.1, * p &lt; 0.05, ** p &lt; 0.01, *** p &lt; 0.001</td></tr></tfoot>
        <tbody>
                <tr>
                  <td data-row="1" data-col="1">(Intercept)</td>
                  <td data-row="1" data-col="2">7.424</td>
                  <td data-row="1" data-col="3">13.085***</td>
                </tr>
                <tr>
                  <td data-row="2" data-col="1"></td>
                  <td data-row="2" data-col="2">(5.185)</td>
                  <td data-row="2" data-col="3">(1.348)</td>
                </tr>
                <tr>
                  <td data-row="3" data-col="1">age</td>
                  <td data-row="3" data-col="2">0.123</td>
                  <td data-row="3" data-col="3"></td>
                </tr>
                <tr>
                  <td data-row="4" data-col="1"></td>
                  <td data-row="4" data-col="2">(0.108)</td>
                  <td data-row="4" data-col="3"></td>
                </tr>
                <tr>
                  <td data-row="5" data-col="1">prenumb</td>
                  <td data-row="5" data-col="2">0.781***</td>
                  <td data-row="5" data-col="3">0.812***</td>
                </tr>
                <tr>
                  <td data-row="6" data-col="1"></td>
                  <td data-row="6" data-col="2">(0.064)</td>
                  <td data-row="6" data-col="3">(0.057)</td>
                </tr>
                <tr>
                  <td data-row="7" data-col="1">Num.Obs.</td>
                  <td data-row="7" data-col="2">240</td>
                  <td data-row="7" data-col="3">240</td>
                </tr>
                <tr>
                  <td data-row="8" data-col="1">R2</td>
                  <td data-row="8" data-col="2">0.459</td>
                  <td data-row="8" data-col="3">0.456</td>
                </tr>
                <tr>
                  <td data-row="9" data-col="1">R2 Adj.</td>
                  <td data-row="9" data-col="2">0.455</td>
                  <td data-row="9" data-col="3">0.454</td>
                </tr>
                <tr>
                  <td data-row="10" data-col="1">AIC</td>
                  <td data-row="10" data-col="2">1766.0</td>
                  <td data-row="10" data-col="3">1765.3</td>
                </tr>
                <tr>
                  <td data-row="11" data-col="1">BIC</td>
                  <td data-row="11" data-col="2">1779.9</td>
                  <td data-row="11" data-col="3">1775.7</td>
                </tr>
                <tr>
                  <td data-row="12" data-col="1">Log.Lik.</td>
                  <td data-row="12" data-col="2">-878.998</td>
                  <td data-row="12" data-col="3">-879.643</td>
                </tr>
                <tr>
                  <td data-row="13" data-col="1">F</td>
                  <td data-row="13" data-col="2">100.629</td>
                  <td data-row="13" data-col="3">199.747</td>
                </tr>
                <tr>
                  <td data-row="14" data-col="1">RMSE</td>
                  <td data-row="14" data-col="2">9.43</td>
                  <td data-row="14" data-col="3">9.45</td>
                </tr>
        </tbody>
      </table>
    </div>
<!-- hack to avoid NA insertion in last line -->
</div>
</div>
<p>Very little has changed compared to the model with both predictors: the coefficient for prenumb and R-squared are almost the same with or without age in the model.</p>
<section id="donations-religion-and-income-1" class="level3">
<h3 class="anchored" data-anchor-id="donations-religion-and-income-1">Donations, religion, and income</h3>
<section id="donations-by-religion-controlling-for-income" class="level4">
<h4 class="anchored" data-anchor-id="donations-by-religion-controlling-for-income">2. Donations by religion, controlling for income</h4>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>donations <span class="ot">&lt;-</span> <span class="fu">read_dta</span>(<span class="st">"data/donations.dta"</span>)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>donations <span class="sc">|&gt;</span>  </span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tabyl</span>(religion)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> religion   n    percent
        1 222 0.40808824
        2 118 0.21691176
        3  89 0.16360294
        4  65 0.11948529
        5  31 0.05698529
        6  19 0.03492647</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print_labels</span>(donations<span class="sc">$</span>religion)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Labels:
 value      label
     1       none
     2   catholic
     3   reformed
     4 rereformed
     5      islam
     6       misc</code></pre>
</div>
</div>
<p>Let’s convert the <code>misc</code> values to missing, then convert the variable to factor.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>donations <span class="ot">&lt;-</span> donations <span class="sc">|&gt;</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>            <span class="fu">mutate</span>(<span class="at">religion =</span> <span class="fu">na_if</span>(religion, <span class="dv">6</span>),</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>                   <span class="at">religion =</span> <span class="fu">factor</span>(religion,</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>                                     <span class="at">levels =</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>,</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>                                     <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"none"</span>, <span class="st">"catholic"</span>, <span class="st">"reformed"</span>,</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>                                                <span class="st">"rereformed"</span>, <span class="st">"islam"</span>))) </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>fit_rel <span class="ot">&lt;-</span> <span class="fu">lm</span>(donation <span class="sc">~</span> religion <span class="sc">+</span> inc, <span class="at">data =</span> donations)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit_rel)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = donation ~ religion + inc, data = donations)

Residuals:
    Min      1Q  Median      3Q     Max 
-2.5167 -0.7217 -0.2464  0.3815  3.9845 

Coefficients:
                   Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)        -1.52013    0.22139  -6.866 1.89e-11 ***
religioncatholic    0.57641    0.12882   4.474 9.42e-06 ***
religionreformed    0.48154    0.14253   3.379 0.000783 ***
religionrereformed  1.92051    0.15966  12.029  &lt; 2e-16 ***
religionislam      -0.03782    0.21675  -0.174 0.861553    
inc                 0.46106    0.04638   9.941  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.13 on 519 degrees of freedom
  (19 observations deleted due to missingness)
Multiple R-squared:  0.3398,    Adjusted R-squared:  0.3334 
F-statistic: 53.42 on 5 and 519 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>There are differences in the average donations of the various religious groups. The null hypothesis that R-squared = 0 (p-value of the F-test) is rejected. From the coefficients we learn that there are significant differences in average donations between catholics and the reference category (none), between reformed and none, and between rereformed and none. There is no evidence of a difference in average donation between islam and none.</p>
</section>
<section id="pairwise-comparisons" class="level4">
<h4 class="anchored" data-anchor-id="pairwise-comparisons">3. Pairwise comparisons</h4>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">avg_comparisons</span>(fit_rel, <span class="at">variables =</span> <span class="fu">list</span>(<span class="at">religion =</span> <span class="st">"pairwise"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
              Contrast Estimate Std. Error      z Pr(&gt;|z|)     S  2.5 % 97.5 %
 catholic - none         0.5764      0.129  4.474  &lt; 0.001  17.0  0.324  0.829
 islam - catholic       -0.6142      0.228 -2.693  0.00709   7.1 -1.061 -0.167
 islam - none           -0.0378      0.217 -0.174  0.86149   0.2 -0.463  0.387
 islam - reformed       -0.5194      0.236 -2.197  0.02804   5.2 -0.983 -0.056
 islam - rereformed     -1.9583      0.247 -7.927  &lt; 0.001  48.7 -2.443 -1.474
 reformed - catholic    -0.0949      0.160 -0.594  0.55248   0.9 -0.408  0.218
 reformed - none         0.4815      0.143  3.379  &lt; 0.001  10.4  0.202  0.761
 rereformed - catholic   1.3441      0.175  7.679  &lt; 0.001  45.8  1.001  1.687
 rereformed - none       1.9205      0.160 12.029  &lt; 0.001 108.3  1.608  2.233
 rereformed - reformed   1.4390      0.184  7.799  &lt; 0.001  47.2  1.077  1.801

Term: religion
Type: response</code></pre>
</div>
</div>
<p>There is a significant difference in donations between rereformed and reformed.</p>
</section>
<section id="proportion-of-income-donated" class="level4">
<h4 class="anchored" data-anchor-id="proportion-of-income-donated">4. Proportion of income donated</h4>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(donations<span class="sc">$</span>donation)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> num [1:544] 0.3624 0.00168 0.33789 0.26711 0.46771 ...
 - attr(*, "label")= chr "donation per year (1000dfl)"
 - attr(*, "format.stata")= chr "%9.0g"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(donations<span class="sc">$</span>inc)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> num [1:544] 3.47 4.3 4.54 4.39 4.54 ...
 - attr(*, "label")= chr "net income per month (1000dfl)"
 - attr(*, "format.stata")= chr "%9.0g"</code></pre>
</div>
</div>
<p>Donation is recorded per year, income is recorded per month. So we have to divide donation by 12 top get the monthly amount. As both are in thousands, it does not make a difference whether or not we multiply both by 1000.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>donations <span class="ot">&lt;-</span> donations <span class="sc">|&gt;</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">propdon =</span> (donation <span class="sc">/</span> <span class="dv">12</span>) <span class="sc">/</span> inc,</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>donations <span class="sc">|&gt;</span></span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">skim</span>(propdon)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Data summary</caption>
<tbody>
<tr class="odd">
<td style="text-align: left;">Name</td>
<td style="text-align: left;">donations</td>
</tr>
<tr class="even">
<td style="text-align: left;">Number of rows</td>
<td style="text-align: left;">544</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Number of columns</td>
<td style="text-align: left;">14</td>
</tr>
<tr class="even">
<td style="text-align: left;">_______________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Column type frequency:</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">numeric</td>
<td style="text-align: left;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">________________________</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Group variables</td>
<td style="text-align: left;">None</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table class="caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 18%">
<col style="width: 13%">
<col style="width: 18%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 3%">
<col style="width: 5%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 7%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">skim_variable</th>
<th style="text-align: right;">n_missing</th>
<th style="text-align: right;">complete_rate</th>
<th style="text-align: right;">mean</th>
<th style="text-align: right;">sd</th>
<th style="text-align: right;">p0</th>
<th style="text-align: right;">p25</th>
<th style="text-align: right;">p50</th>
<th style="text-align: right;">p75</th>
<th style="text-align: right;">p100</th>
<th style="text-align: left;">hist</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">propdon</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.02</td>
<td style="text-align: right;">0.02</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.01</td>
<td style="text-align: right;">0.03</td>
<td style="text-align: right;">0.08</td>
<td style="text-align: left;">▇▂▁▁▁</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The mean proportion of monthly income donated is about 0.02. The sd is relatively large compared to the mean, which suggests substantial variation in the proportion of income that is donated.</p>
</section>
<section id="proportion-donated-by-religion" class="level4">
<h4 class="anchored" data-anchor-id="proportion-donated-by-religion">5. Proportion donated by religion</h4>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>fit_propdon <span class="ot">&lt;-</span> <span class="fu">lm</span>(propdon <span class="sc">~</span> religion, <span class="at">data =</span> donations)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit_propdon)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = propdon ~ religion, data = donations)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.042965 -0.008909 -0.007011  0.006720  0.059807 

Coefficients:
                     Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)         0.0089092  0.0012976   6.866 1.89e-11 ***
religioncatholic    0.0102488  0.0022026   4.653 4.16e-06 ***
religionreformed    0.0112218  0.0024257   4.626 4.71e-06 ***
religionrereformed  0.0356314  0.0027267  13.068  &lt; 2e-16 ***
religionislam      -0.0008189  0.0037070  -0.221    0.825    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.01933 on 520 degrees of freedom
  (19 observations deleted due to missingness)
Multiple R-squared:  0.258, Adjusted R-squared:  0.2523 
F-statistic: 45.21 on 4 and 520 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">avg_comparisons</span>(fit_propdon, <span class="at">variables =</span> <span class="fu">list</span>(<span class="at">religion =</span> <span class="st">"pairwise"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
              Contrast  Estimate Std. Error      z Pr(&gt;|z|)     S    2.5 %
 catholic - none        0.010249    0.00220  4.653  &lt; 0.001  18.2  0.00593
 islam - catholic      -0.011068    0.00390 -2.836  0.00456   7.8 -0.01872
 islam - none          -0.000819    0.00371 -0.221  0.82517   0.3 -0.00808
 islam - reformed      -0.012041    0.00403 -2.986  0.00282   8.5 -0.01994
 islam - rereformed    -0.036450    0.00422 -8.637  &lt; 0.001  57.3 -0.04472
 reformed - catholic    0.000973    0.00271  0.358  0.72001   0.5 -0.00435
 reformed - none        0.011222    0.00243  4.626  &lt; 0.001  18.0  0.00647
 rereformed - catholic  0.025383    0.00299  8.499  &lt; 0.001  55.5  0.01953
 rereformed - none      0.035631    0.00273 13.068  &lt; 0.001 127.2  0.03029
 rereformed - reformed  0.024410    0.00315  7.738  &lt; 0.001  46.5  0.01823
   97.5 %
  0.01457
 -0.00342
  0.00645
 -0.00414
 -0.02818
  0.00629
  0.01598
  0.03124
  0.04098
  0.03059

Term: religion
Type: response</code></pre>
</div>
</div>
<p>No significant differences are found between islam and none, and between catholics and reformed (the 95% confidence interval for these pairwise differences includes 0). There is evidence of difference for all other comparisons.</p>
</section>
<section id="proportion-donated-and-income" class="level4">
<h4 class="anchored" data-anchor-id="proportion-donated-and-income">6. Proportion donated and income</h4>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>fit_propdon_inc_rel <span class="ot">&lt;-</span> <span class="fu">lm</span>(propdon <span class="sc">~</span> inc <span class="sc">+</span> religion, <span class="at">data =</span> donations)</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit_propdon_inc_rel)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = propdon ~ inc + religion, data = donations)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.040982 -0.011259 -0.005486  0.006462  0.056252 

Coefficients:
                     Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)        -0.0100917  0.0036850  -2.739  0.00638 ** 
inc                 0.0042372  0.0007720   5.489 6.35e-08 ***
religioncatholic    0.0105776  0.0021443   4.933 1.09e-06 ***
religionreformed    0.0099187  0.0023724   4.181 3.41e-05 ***
religionrereformed  0.0348148  0.0026575  13.100  &lt; 2e-16 ***
religionislam      -0.0004735  0.0036079  -0.131  0.89564    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.01881 on 519 degrees of freedom
  (19 observations deleted due to missingness)
Multiple R-squared:  0.2987,    Adjusted R-squared:  0.292 
F-statistic: 44.22 on 5 and 519 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>There is evidence that donations increase with income, even controlling for religion (b = 0.00424, t = 5.49, p &lt; 0.001). For each unit (1000) increase in monthly income, the proportion of income donated increases by about 0.004 (or the percentage increases by 0.4 percentage points).</p>
</section>
<section id="does-the-religion-effect-differ-by-gender" class="level4">
<h4 class="anchored" data-anchor-id="does-the-religion-effect-differ-by-gender">7. Does the religion effect differ by gender?</h4>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>fit_male_rel <span class="ot">&lt;-</span> <span class="fu">lm</span>(propdon <span class="sc">~</span> male <span class="sc">*</span> religion, <span class="at">data =</span> donations)</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit_male_rel)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = propdon ~ male * religion, data = donations)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.042468 -0.011292 -0.006108  0.007241  0.061761 

Coefficients:
                         Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)              0.006386   0.001839   3.473 0.000559 ***
male                     0.005001   0.002589   1.931 0.053973 .  
religioncatholic         0.013554   0.002888   4.693 3.46e-06 ***
religionreformed         0.012866   0.003268   3.938 9.36e-05 ***
religionrereformed       0.033962   0.003828   8.871  &lt; 2e-16 ***
religionislam            0.001505   0.005027   0.299 0.764808    
male:religioncatholic   -0.007146   0.004507  -1.586 0.113459    
male:religionreformed   -0.002943   0.004877  -0.603 0.546516    
male:religionrereformed  0.003515   0.005441   0.646 0.518496    
male:religionislam      -0.004559   0.007427  -0.614 0.539577    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.01929 on 515 degrees of freedom
  (19 observations deleted due to missingness)
Multiple R-squared:  0.2687,    Adjusted R-squared:  0.2559 
F-statistic: 21.02 on 9 and 515 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>There is no evidence that the effect of religion on donations differs for men and women (the interaction terms are not significant).</p>
</section>
<section id="does-the-income-effect-differ-by-religion" class="level4">
<h4 class="anchored" data-anchor-id="does-the-income-effect-differ-by-religion">8. Does the income effect differ by religion?</h4>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>fit_inc_rel <span class="ot">&lt;-</span> <span class="fu">lm</span>(propdon <span class="sc">~</span> inc <span class="sc">*</span> religion, <span class="at">data =</span> donations)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit_inc_rel)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = propdon ~ inc * religion, data = donations)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.041565 -0.011496 -0.004980  0.006665  0.055997 

Coefficients:
                         Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)            -0.0129977  0.0054123  -2.401  0.01668 *  
inc                     0.0048853  0.0011736   4.163 3.69e-05 ***
religioncatholic        0.0100851  0.0088933   1.134  0.25732    
religionreformed        0.0276856  0.0113102   2.448  0.01470 *  
religionrereformed      0.0360811  0.0122500   2.945  0.00337 ** 
religionislam           0.0069804  0.0152332   0.458  0.64697    
inc:religioncatholic    0.0001232  0.0019460   0.063  0.94956    
inc:religionreformed   -0.0037493  0.0023450  -1.599  0.11046    
inc:religionrereformed -0.0002975  0.0025785  -0.115  0.90821    
inc:religionislam      -0.0016810  0.0033536  -0.501  0.61641    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.01883 on 515 degrees of freedom
  (19 observations deleted due to missingness)
Multiple R-squared:  0.3028,    Adjusted R-squared:  0.2906 
F-statistic: 24.85 on 9 and 515 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>There is no evidence that the effect of income on donations varies between the religious denominations.</p>
</section>
<section id="age-and-life-events" class="level4">
<h4 class="anchored" data-anchor-id="age-and-life-events">9. Age and life events</h4>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>fit_age_life <span class="ot">&lt;-</span> <span class="fu">lm</span>(propdon <span class="sc">~</span> age<span class="sc">*</span>lifevent, <span class="at">data =</span> donations)</span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit_age_life)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = propdon ~ age * lifevent, data = donations)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.034080 -0.012031 -0.007586  0.007675  0.066753 

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)   
(Intercept)   0.0023225  0.0036756   0.632  0.52773   
age           0.0002673  0.0000922   2.900  0.00389 **
lifevent      0.0247355  0.0093137   2.656  0.00815 **
age:lifevent -0.0001476  0.0002047  -0.721  0.47116   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.02045 on 540 degrees of freedom
Multiple R-squared:  0.1674,    Adjusted R-squared:  0.1628 
F-statistic: 36.19 on 3 and 540 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>There is no evidence that the effect of a life event on donations is larger for older than for younger people.</p>
</section>
<section id="does-the-income-effect-vary-with-age" class="level4">
<h4 class="anchored" data-anchor-id="does-the-income-effect-vary-with-age">10. Does the income effect vary with age?</h4>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>fit_age_inc <span class="ot">&lt;-</span> <span class="fu">lm</span>(propdon <span class="sc">~</span> age <span class="sc">*</span> inc, <span class="at">data =</span> donations)</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit_age_inc)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = propdon ~ age * inc, data = donations)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.029595 -0.014661 -0.008415  0.009764  0.066558 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)
(Intercept) -4.868e-03  1.652e-02  -0.295    0.768
age          1.551e-04  3.761e-04   0.412    0.680
inc          2.756e-03  4.005e-03   0.688    0.492
age:inc      2.020e-05  8.484e-05   0.238    0.812

Residual standard error: 0.02161 on 540 degrees of freedom
Multiple R-squared:  0.07047,   Adjusted R-squared:  0.06531 
F-statistic: 13.65 on 3 and 540 DF,  p-value: 1.36e-08</code></pre>
</div>
</div>
<p>There is no evidence that the effect of monthly income on donations varies with age.</p>
</section>
<section id="does-the-income-effect-differ-between-men-and-women" class="level4">
<h4 class="anchored" data-anchor-id="does-the-income-effect-differ-between-men-and-women">11. Does the income effect differ between men and women?</h4>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>fit_male_inc <span class="ot">&lt;-</span> <span class="fu">lm</span>(propdon <span class="sc">~</span> male <span class="sc">*</span> inc, <span class="at">data =</span> donations)</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit_male_inc)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = propdon ~ male * inc, data = donations)

Residuals:
      Min        1Q    Median        3Q       Max 
-0.029906 -0.014947 -0.008675  0.010361  0.067742 

Coefficients:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -0.0066803  0.0054306  -1.230    0.219    
male        -0.0002139  0.0088271  -0.024    0.981    
inc          0.0055309  0.0012532   4.414 1.23e-05 ***
male:inc    -0.0002768  0.0018640  -0.149    0.882    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.02171 on 540 degrees of freedom
Multiple R-squared:  0.06198,   Adjusted R-squared:  0.05677 
F-statistic: 11.89 on 3 and 540 DF,  p-value: 1.491e-07</code></pre>
</div>
</div>
<p>There is no evidence that the effect of monthly income on donations differs for men and women.</p>
</section>
<section id="a-three-way-interaction" class="level4">
<h4 class="anchored" data-anchor-id="a-three-way-interaction">12. A three-way interaction</h4>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>fit_inc_male_religion <span class="ot">&lt;-</span> <span class="fu">lm</span>(propdon <span class="sc">~</span> male <span class="sc">*</span> inc <span class="sc">*</span> religion, <span class="at">data =</span> donations)</span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit_inc_male_religion)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = propdon ~ male * inc * religion, data = donations)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.04104 -0.01119 -0.00453  0.00743  0.05770 

Coefficients:
                             Estimate Std. Error t value Pr(&gt;|t|)   
(Intercept)                 -0.009004   0.007554  -1.192  0.23384   
male                        -0.006286   0.011511  -0.546  0.58523   
inc                          0.003748   0.001787   2.097  0.03645 * 
religioncatholic            -0.003512   0.011774  -0.298  0.76558   
religionreformed             0.018253   0.014448   1.263  0.20703   
religionrereformed           0.050599   0.017604   2.874  0.00422 **
religionislam               -0.001237   0.020540  -0.060  0.95201   
male:inc                     0.001747   0.002502   0.698  0.48535   
male:religioncatholic        0.019717   0.019828   0.994  0.32050   
male:religionreformed        0.026243   0.025311   1.037  0.30031   
male:religionrereformed     -0.021150   0.025977  -0.814  0.41593   
male:religionislam           0.009172   0.035297   0.260  0.79508   
inc:religioncatholic         0.004165   0.002786   1.495  0.13552   
inc:religionreformed        -0.001534   0.003207  -0.478  0.63269   
inc:religionrereformed      -0.004035   0.004006  -1.007  0.31430   
inc:religionislam            0.000848   0.005029   0.169  0.86616   
male:inc:religioncatholic   -0.006241   0.004223  -1.478  0.14005   
male:inc:religionreformed   -0.005491   0.005137  -1.069  0.28561   
male:inc:religionrereformed  0.005447   0.005490   0.992  0.32157   
male:inc:religionislam      -0.003179   0.007601  -0.418  0.67600   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.01882 on 505 degrees of freedom
  (19 observations deleted due to missingness)
Multiple R-squared:  0.3175,    Adjusted R-squared:  0.2918 
F-statistic: 12.36 on 19 and 505 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>There is no evidence that possible gender differences in the effect of monthly income on donations vary with religion (the three-way interaction terms are not significant).</p>
</section>
</section>
<section id="occupational-prestige-and-education-1" class="level3">
<h3 class="anchored" data-anchor-id="occupational-prestige-and-education-1">Occupational prestige and education</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>gss91 <span class="ot">&lt;-</span> <span class="fu">read_dta</span>(<span class="st">"data/gss91_extended.dta"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<section id="linear-and-quadratic-fits" class="level4">
<h4 class="anchored" data-anchor-id="linear-and-quadratic-fits">13. Linear and quadratic fits</h4>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(gss91, <span class="fu">aes</span>(<span class="at">x =</span> educ, <span class="at">y =</span> prestg80)) <span class="sc">+</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">formula =</span> y <span class="sc">~</span> x, <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">"blue"</span>) <span class="sc">+</span></span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">formula =</span> y <span class="sc">~</span> x <span class="sc">+</span> <span class="fu">I</span>(x<span class="sc">*</span>x), <span class="at">se =</span> <span class="cn">FALSE</span>, <span class="at">color =</span> <span class="st">"red"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 102 rows containing non-finite outside the scale range
(`stat_smooth()`).
Removed 102 rows containing non-finite outside the scale range
(`stat_smooth()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 102 rows containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="multiple_regression_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="quadratic-model-with-controls" class="level4">
<h4 class="anchored" data-anchor-id="quadratic-model-with-controls">14. Quadratic model with controls</h4>
<p>To fit a quadratic line we can either create the squared term beforehand (i.e.&nbsp;create <code>educ2 = educ*educ</code>, then include both <code>educ</code> and <code>educ2</code> in the equation) or specify the squared term with the syntax <code>I(educ*educ)</code>. (Note that simply including <code>educ*educ</code>, as we would do for an interaction of different variables, does not work. Thus the need for <code>I()</code>).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>fit_quad <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>  prestg80 <span class="sc">~</span> educ <span class="sc">+</span> <span class="fu">I</span>(educ<span class="sc">^</span><span class="dv">2</span>) <span class="sc">+</span> <span class="fu">factor</span>(race) <span class="sc">+</span> <span class="fu">factor</span>(region) <span class="sc">+</span> <span class="fu">factor</span>(sex),</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> gss91</span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(fit_quad)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = prestg80 ~ educ + I(educ^2) + factor(race) + factor(region) + 
    factor(sex), data = gss91)

Residuals:
    Min      1Q  Median      3Q     Max 
-39.056  -7.644   0.021   7.178  32.372 

Coefficients:
                Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)     34.62120    3.40084  10.180  &lt; 2e-16 ***
educ            -1.08111    0.52238  -2.070   0.0387 *  
I(educ^2)        0.13022    0.02015   6.464 1.41e-10 ***
factor(race)2   -4.03072    0.91363  -4.412 1.10e-05 ***
factor(race)3   -3.29608    1.72685  -1.909   0.0565 .  
factor(region)2 -0.42017    0.71961  -0.584   0.5594    
factor(region)3  0.22872    0.70219   0.326   0.7447    
factor(sex)2    -0.30483    0.58995  -0.517   0.6054    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 10.94 on 1407 degrees of freedom
  (102 observations deleted due to missingness)
Multiple R-squared:  0.3036,    Adjusted R-squared:  0.3001 
F-statistic: 87.63 on 7 and 1407 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>The educ-squared term is significant, so there is evidence of a quadratic relationship, controlling for race, region, and sex.</p>
</section>
<section id="turning-point" class="level4">
<h4 class="anchored" data-anchor-id="turning-point">15. Turning point</h4>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>b_educ <span class="ot">&lt;-</span> <span class="fu">coef</span>(fit_quad)[<span class="st">"educ"</span>]</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>b_educ2 <span class="ot">&lt;-</span> <span class="fu">coef</span>(fit_quad)[<span class="st">"I(educ^2)"</span>]</span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a>turning_point <span class="ot">&lt;-</span> <span class="sc">-</span>b_educ <span class="sc">/</span> (<span class="dv">2</span> <span class="sc">*</span> b_educ2)</span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a>turning_point</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>    educ 
4.151102 </code></pre>
</div>
</div>
<p>Since the coefficient for the squared term is greater than zero, the relation is U-shaped. This was already suggested by the scatterplot (though that plot did not include statistical controls). We conclude that around 4 years of education corresponds to the lowest predicted prestige.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>gss91 <span class="sc">|&gt;</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(educ <span class="sc">&lt;=</span> <span class="dv">4</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 12 × 26
   sex        race      region   life     sibs  childs age   educ  paeduc maeduc
   &lt;dbl+lbl&gt;  &lt;dbl+lbl&gt; &lt;dbl+lb&gt; &lt;dbl+lb&gt; &lt;dbl&gt; &lt;dbl+&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl+&gt; &lt;dbl+&gt;
 1 1 [male]   3 [other] 3 [west]  2 [rou… 10    4      49    4     4      3     
 2 1 [male]   1 [white] 1 [nort… NA       11    4      62    3     8      8     
 3 1 [male]   1 [white] 1 [nort…  2 [rou…  7    4      89    4     8      8     
 4 2 [female] 2 [black] 2 [sout… NA        5    3      72    4     1      4     
 5 1 [male]   2 [black] 2 [sout… NA        7    3      34    4     4      8     
 6 2 [female] 1 [white] 2 [sout…  2 [rou…  8    4      63    0     0      1     
 7 2 [female] 2 [black] 2 [sout… NA        1    0      82    3     0      0     
 8 2 [female] 1 [white] 3 [west]  1 [exc…  6    0      53    3     0      0     
 9 2 [female] 1 [white] 2 [sout…  3 [dul…  4    4      89    0     0      0     
10 1 [male]   1 [white] 2 [sout…  2 [rou…  4    4      50    3     3      2     
11 1 [male]   2 [black] 2 [sout…  1 [exc…  9    0      59    4     0      0     
12 1 [male]   3 [other] 2 [sout…  2 [rou…  5    1      61    3     0      1     
# ℹ 16 more variables: speduc &lt;dbl+lbl&gt;, prestg80 &lt;dbl+lbl&gt;,
#   occcat80 &lt;dbl+lbl&gt;, work1 &lt;dbl+lbl&gt;, work2 &lt;dbl+lbl&gt;, work3 &lt;dbl+lbl&gt;,
#   work4 &lt;dbl+lbl&gt;, work5 &lt;dbl+lbl&gt;, work6 &lt;dbl+lbl&gt;, work7 &lt;dbl+lbl&gt;,
#   work8 &lt;dbl+lbl&gt;, work9 &lt;dbl+lbl&gt;, workprob &lt;dbl&gt;, upmobil &lt;dbl&gt;,
#   pdissim &lt;dbl&gt;, happy &lt;dbl&gt;</code></pre>
</div>
</div>
<p>Only a small number of subjects have educ values at or below the turning point (about 12 out of roughly 1500). It is highly unlikely that prestige is actually higher with 1 or 2 years of education than# with 4 years; the model most plausibly applies for 4 and more years of education. We therefore abstain from interpreting the turning point itself, and conclude instead that, over the range where most of the data lie, prestige increases in education at an increasing rate.</p>
</section>
</section>
</section>
</div>
</div>
</div>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/SaSR03\.github\.io\/sasr03\.github\.io\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>